"""The site header, shared by the three archive builders.

The archive is generated by three independent scripts (build-archive, build-wiki,
build-gallery) that each emit their own stylesheet, so without this they each
grew their own header and the archive looked like three sites stapled together.
It is also the same header as the simulator's, deliberately: the archive is part
of that site, not a separate property, and the one navigational failure this
whole exercise exists to undo is a page you cannot get back from.

Two things every page must therefore carry:

  * archive-relevant links -- the wiki, the die photography, the original site
  * a way back to the simulator, which is what `nav-cta` is

The markup matches web/index.html exactly (`.site-head` > `nav` > `.mark`,
`.navlinks`, `.nav-cta`, `.menu-btn`) so that web/site-nav.js drives the
disclosure menu on both. That file is copied into the archive rather than
reimplemented -- see build-archive.py.
"""

from __future__ import annotations

import html
from collections.abc import Sequence

# Where the simulator lives, from the archive's point of view. Absolute because
# the archive is served at /archive/ and the simulator at the site root, so no
# relative path from inside the archive can reach it.
SIMULATOR = "/"

# Palette variables are supplied by each builder's own stylesheet (--fg, --muted,
# --accent, --line, --space, --mono). This block adds only what the header needs,
# and is appended to each of them.
CSS = """
.site-head{position:sticky;top:0;z-index:30;backdrop-filter:blur(12px);
background:color-mix(in srgb,var(--space) 86%,transparent);
border-bottom:2px solid color-mix(in srgb,var(--line) 55%,transparent)}
.site-head .wrap{position:relative;padding-top:0;padding-bottom:0;max-width:78rem}
.site-head nav{display:flex;align-items:center;gap:.9rem;height:4.25rem}
.site-head a{text-decoration:none}
.mark{font-weight:900;font-size:1.1rem;letter-spacing:-.02em;color:var(--fg);
white-space:nowrap;display:inline-flex;align-items:center;gap:.5rem}
.mark .n{font-family:var(--mono);font-weight:700;color:var(--accent)}
.mark .tagword{font-family:var(--mono);font-size:.58rem;font-weight:700;
letter-spacing:.14em;text-transform:uppercase;color:var(--muted);
border:1px solid color-mix(in srgb,var(--line) 70%,transparent);
border-radius:.25rem;padding:.15rem .35rem}
.navlinks{display:none}
.navlinks a{padding:.7rem .2rem;color:var(--fg);font-weight:700;
border-bottom:1px solid color-mix(in srgb,var(--line) 35%,transparent)}
.navlinks a:hover{color:var(--gold)}
.navlinks a[aria-current=page]{color:var(--accent)}
.site-head .nav-cta{margin-left:auto;display:inline-flex;align-items:center;
justify-content:center;min-height:2.75rem;padding:.4rem .95rem;font-size:.85rem;
font-weight:800;border:2px solid var(--accent);border-radius:.375rem;
background:var(--accent);color:#06121f;box-shadow:5px 5px 0 rgba(2,6,16,.5);
transition:.15s;white-space:nowrap}
.site-head .nav-cta:hover{border-color:var(--gold);background:var(--gold)}
.site-head .nav-cta:active{transform:translate(2px,2px);
box-shadow:3px 3px 0 rgba(2,6,16,.5)}
.menu-btn{display:inline-flex;align-items:center;gap:.5rem;min-height:2.75rem;
padding:.4rem .8rem;border:2px solid color-mix(in srgb,var(--line) 80%,transparent);
border-radius:.375rem;background:transparent;color:var(--muted);cursor:pointer;
font-family:var(--mono);font-size:.7rem;font-weight:700;letter-spacing:.12em;
text-transform:uppercase;transition:.15s}
.menu-btn:hover{border-color:var(--gold);color:var(--gold)}
.menu-btn .mi{display:grid;gap:3px;width:.95rem}
.menu-btn .mi i{display:block;height:2px;background:currentColor;border-radius:2px;
transition:.15s}
.menu-btn[aria-expanded=true]{border-color:var(--accent);color:var(--fg);
background:color-mix(in srgb,var(--accent) 16%,transparent)}
.menu-btn[aria-expanded=true] .mi i:nth-child(1){transform:translateY(5px) rotate(45deg)}
.menu-btn[aria-expanded=true] .mi i:nth-child(2){opacity:0}
.menu-btn[aria-expanded=true] .mi i:nth-child(3){transform:translateY(-5px) rotate(-45deg)}
.site-head.open .navlinks{display:grid;position:absolute;top:100%;left:0;right:0;
z-index:40;padding:.5rem 1.25rem 1rem;
background:color-mix(in srgb,var(--space) 96%,transparent);backdrop-filter:blur(12px);
border-bottom:2px solid color-mix(in srgb,var(--line) 55%,transparent);
box-shadow:0 14px 24px rgba(2,6,16,.5)}
@media(min-width:62rem){
.menu-btn{display:none}
.navlinks{display:flex;align-items:center;gap:1.4rem;margin-left:1.5rem}
.navlinks a{border:0;padding:0;font-size:.95rem;font-weight:600;color:var(--muted)}
.navlinks a:hover{color:var(--fg)}
.navlinks a[aria-current=page]{color:var(--accent)}}
/* Below 384px the wordmark, call to action and menu together want more width
   than the viewport has, and the overflow escapes the header rather than being
   clipped. The CTA goes: the menu still lists the simulator. */
@media(max-width:24rem){.site-head .nav-cta{display:none}
.mark .tagword{display:none}}
"""


def header(root: str, links: Sequence[tuple[str, str]], active: str = "") -> str:
    """Render the header.

    `root` is the relative prefix that reaches archive/public/ from the page
    being written ("" at the top, "../" inside wiki/ or gallery/). `links` are
    (label, href) with hrefs already relative to `root`. `active` marks the
    current section for `aria-current`.
    """
    # Built with %-formatting rather than an f-string: the marker contains double
    # quotes, and a backslash inside an f-string expression is a syntax error
    # before Python 3.12.
    current = ' aria-current="page"'
    # An href starting with "/" or a scheme is already absolute and must not be
    # prefixed: the archive nests two deep, so "../" in front of "/schematic"
    # would point at a page that does not exist. Only archive-internal links are
    # relative to `root`.
    items = "\n        ".join(
        '<a href="%s%s"%s>%s</a>'
        % (
            "" if href.startswith(("/", "http://", "https://")) else root,
            href,
            current if label == active else "",
            html.escape(label),
        )
        for label, href in links
    )
    return f"""<header class="site-head">
  <div class="wrap">
    <nav aria-label="Site">
      <a class="mark" href="{root}index.html"><span
        >Visual<span class="n">6502</span></span><span class="tagword">archive</span></a>
      <div class="navlinks">
        {items}
      </div>
      <a class="nav-cta" href="{SIMULATOR}">Simulator</a>
      <button class="menu-btn" type="button" aria-expanded="false" aria-label="Menu">
        <span class="mi" aria-hidden="true"><i></i><i></i><i></i></span>
        <span class="mtxt">Menu</span>
      </button>
    </nav>
  </div>
</header>"""


# The links every archive page carries. `build-wiki.py` inserts its own Images
# entry into a copy of this; nothing else varies.
LINKS: tuple[tuple[str, str], ...] = (
    ("Overview", "index.html"),
    ("Wiki", "wiki/index.html"),
    ("Die photos", "gallery/index.html"),
    ("Original site", "full/index.html"),
    # Out to the simulator. Absolute, because the archive nests two deep and a
    # relative path would resolve differently on a wiki page than on the index.
    ("Schematic", "/schematic"),
)
