//! Differential test against the original visual6502 JavaScript engine.
//!
//! The oracle is generated by `tools/golden-trace/gen.js`, which runs the
//! reference implementation headlessly and dumps the logic level of all 1725
//! nodes at every half-cycle. Matching register values would only show that the
//! two agree about the 6502; matching every node shows they agree about the
//! *silicon*, which is the claim this project actually makes.
//!
//! Regenerate with:
//!     node tools/golden-trace/gen.js --steps 3000

use std::path::PathBuf;
use std::sync::Arc;

use v6502_netlist::mos6502;
use v6502_sim::{bus::FlatMemory, cpu::Cpu, ReadWrite};

struct Golden {
    program_addr: u16,
    program: Vec<u8>,
    reset_vector: u16,
    rows: Vec<Row>,
}

struct Row {
    half_cycle: u64,
    ab: u16,
    db: u8,
    rw: u8,
    sync: u8,
    pc: u16,
    a: u8,
    x: u8,
    y: u8,
    s: u8,
    p: u8,
    state: String,
}

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tools/golden-trace/golden.txt")
}

fn load_golden() -> Option<Golden> {
    let text = std::fs::read_to_string(golden_path()).ok()?;
    let mut program_addr = 0u16;
    let mut program = Vec::new();
    let mut reset_vector = 0u16;
    let mut rows = Vec::new();

    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# ") {
            let mut it = rest.split_whitespace();
            match (it.next(), it.next()) {
                (Some("program_addr"), Some(v)) => program_addr = v.parse().unwrap(),
                (Some("reset_vector"), Some(v)) => reset_vector = v.parse().unwrap(),
                (Some("program"), Some(v)) => {
                    program = (0..v.len())
                        .step_by(2)
                        .map(|i| u8::from_str_radix(&v[i..i + 2], 16).unwrap())
                        .collect()
                }
                _ => {}
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(f.len(), 12, "malformed golden row: {line}");
        let hex = |s: &str| u32::from_str_radix(s, 16).unwrap();
        rows.push(Row {
            half_cycle: f[0].parse().unwrap(),
            ab: hex(f[1]) as u16,
            db: hex(f[2]) as u8,
            rw: f[3].parse().unwrap(),
            sync: f[4].parse().unwrap(),
            pc: hex(f[5]) as u16,
            a: hex(f[6]) as u8,
            x: hex(f[7]) as u8,
            y: hex(f[8]) as u8,
            s: hex(f[9]) as u8,
            p: hex(f[10]) as u8,
            state: f[11].to_string(),
        });
    }
    Some(Golden { program_addr, program, reset_vector, rows })
}

#[test]
fn matches_reference_node_for_node() {
    let Some(golden) = load_golden() else {
        // The oracle is ~5 MB and is itself derived from the CC BY-NC-SA die
        // data, so it is generated rather than committed. Skip rather than fail
        // so `cargo test` works on a fresh clone -- but let CI demand it, since
        // a silently-skipped differential test is worse than none.
        let msg = format!(
            "golden trace not found at {}\n    generate it with: node tools/golden-trace/gen.js --steps 3000",
            golden_path().display()
        );
        assert!(
            std::env::var_os("V6502_REQUIRE_GOLDEN").is_none(),
            "V6502_REQUIRE_GOLDEN is set but the {msg}"
        );
        eprintln!("\n  SKIPPED (differential vs the reference): {msg}\n");
        return;
    };

    let mut mem = FlatMemory::new();
    mem.load(golden.program_addr, &golden.program);
    mem.set_reset_vector(golden.reset_vector);

    let mut cpu = Cpu::new(Arc::new(mos6502()), mem).unwrap();
    cpu.reset();

    for row in &golden.rows {
        let regs = cpu.registers();
        let bus = cpu.bus_state();

        // Compare the whole chip first: a node-level divergence is the root
        // cause, and the architectural fields are downstream symptoms.
        let ours = cpu.state_string();
        if ours != row.state {
            let diverged: Vec<usize> = ours
                .chars()
                .zip(row.state.chars())
                .enumerate()
                .filter(|(_, (a, b))| a != b)
                .map(|(i, _)| i)
                .collect();
            let nl = mos6502();
            let named: Vec<String> = diverged
                .iter()
                .take(12)
                .map(|&n| match nl.name_of(n as u16) {
                    Some(name) => format!("{n} ({name})"),
                    None => n.to_string(),
                })
                .collect();
            panic!(
                "half-cycle {}: {} of {} nodes differ from the reference\n\
                 first divergent nodes: {}\n\
                 ours:      AB={:04x} DB={:02x} PC={:04x} A={:02x} X={:02x} Y={:02x}\n\
                 reference: AB={:04x} DB={:02x} PC={:04x} A={:02x} X={:02x} Y={:02x}",
                row.half_cycle,
                diverged.len(),
                ours.len(),
                named.join(", "),
                bus.addr,
                bus.data,
                regs.pc,
                regs.a,
                regs.x,
                regs.y,
                row.ab,
                row.db,
                row.pc,
                row.a,
                row.x,
                row.y,
            );
        }

        assert_eq!(cpu.half_cycle(), row.half_cycle, "half-cycle counter drifted");
        assert_eq!(bus.addr, row.ab, "AB at half-cycle {}", row.half_cycle);
        assert_eq!(bus.data, row.db, "DB at half-cycle {}", row.half_cycle);
        assert_eq!(
            bus.rw,
            if row.rw == 1 { ReadWrite::Read } else { ReadWrite::Write },
            "RW at half-cycle {}",
            row.half_cycle
        );
        assert_eq!(bus.sync, row.sync == 1, "SYNC at half-cycle {}", row.half_cycle);
        assert_eq!(regs.pc, row.pc, "PC at half-cycle {}", row.half_cycle);
        assert_eq!(regs.a, row.a, "A at half-cycle {}", row.half_cycle);
        assert_eq!(regs.x, row.x, "X at half-cycle {}", row.half_cycle);
        assert_eq!(regs.y, row.y, "Y at half-cycle {}", row.half_cycle);
        assert_eq!(regs.s, row.s, "S at half-cycle {}", row.half_cycle);
        assert_eq!(regs.p, row.p, "P at half-cycle {}", row.half_cycle);

        cpu.half_step();
    }

    // The model should never have hit an electrical contradiction or failed to
    // settle over a run this long.
    let stats = cpu.engine().stats();
    assert_eq!(stats.nonconvergent_settles, 0, "network failed to settle");
    assert_eq!(stats.contested_groups, 0, "pullup and pulldown fought in one group");
}
