//! The compiler front end: read the die through the schematic, emit the
//! kernel as Rust.
//!
//! What is emitted, and only this, so the licence check can hold it to it:
//! numbers. Node and transistor indices, the fold of each recognised gate
//! as a sum of products over node indices, the switch list, and the signal
//! indices the runtime needs. No name from the die's name table reaches the
//! generated file.

use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::PathBuf;

use v6502_netlist::schematic::Schematic;
use v6502_netlist::{mos6502, NodeId, TransId};

fn main() {
    let nl = mos6502();
    let sch = Schematic::derive(&nl);
    let (vss, vcc) = (nl.vss(), nl.vcc());
    let unresolved: HashSet<NodeId> = sch.unresolved.iter().map(|u| u.node).collect();

    // --- the fold -----------------------------------------------------
    struct Fold {
        out: NodeId,
        singles: Vec<NodeId>,
        series: Vec<(NodeId, NodeId, NodeId)>, // (top literal, bottom literal, junction)
    }
    let mut folds: Vec<Fold> = Vec::new();
    let mut absorbed: HashSet<TransId> = HashSet::new();
    let mut junction_of: HashMap<NodeId, usize> = HashMap::new();
    let mut not_folded = 0usize;

    for g in &sch.gates {
        if unresolved.contains(&g.out) {
            not_folded += 1;
            continue;
        }
        let mine: HashSet<TransId> = g.transistors.iter().copied().collect();
        let mut used: HashSet<TransId> = HashSet::new();
        let mut f = Fold { out: g.out, singles: Vec::new(), series: Vec::new() };
        for t in nl.terminals_of(g.out) {
            if !mine.contains(&t.transistor) {
                continue;
            }
            if t.other == vss {
                f.singles.push(nl.transistor_gate(t.transistor));
                used.insert(t.transistor);
            } else {
                let j = t.other;
                for u in nl.terminals_of(j) {
                    if u.other == vss && mine.contains(&u.transistor) {
                        f.series.push((nl.transistor_gate(t.transistor), nl.transistor_gate(u.transistor), j));
                        used.insert(u.transistor);
                    }
                }
                used.insert(t.transistor);
            }
        }
        if used != mine {
            // A reading this fold cannot express: leave the gate as switches
            // rather than fold it wrong.
            not_folded += 1;
            continue;
        }
        for &(_, _, j) in &f.series {
            if let Some(prev) = junction_of.insert(j, folds.len()) {
                assert_eq!(prev, folds.len(), "junction {j} shared by two gates");
            }
        }
        absorbed.extend(mine);
        folds.push(f);
    }

    // --- the switches ---------------------------------------------------
    // Everything not absorbed, minus what can never conduct or never carries
    // drive, with the rail direction the kernel computes per transistor.
    #[derive(PartialEq)]
    enum Flow {
        Both,
        C1ToC2,
        C2ToC1,
    }
    let mut switches: Vec<(TransId, NodeId, NodeId, Flow)> = Vec::new();
    let mut dead = 0usize;
    for t in 0..nl.transistor_count() as TransId {
        if absorbed.contains(&t) {
            continue;
        }
        let (g, a, b) = (nl.transistor_gate(t), nl.transistor_c1(t), nl.transistor_c2(t));
        if g == vss || (nl.is_rail(a) && nl.is_rail(b)) {
            dead += 1;
            continue;
        }
        let flow = match (nl.is_rail(a), nl.is_rail(b)) {
            (true, false) => Flow::C1ToC2,
            (false, true) => Flow::C2ToC1,
            _ => Flow::Both,
        };
        switches.push((t, a, b, flow));
    }

    // --- emit -----------------------------------------------------------
    let mut o = String::new();
    let w = &mut o;
    writeln!(w, "// Generated by build.rs from the die data through Schematic::derive. Do not edit.").unwrap();
    writeln!(w, "pub const NODES: usize = {};", nl.node_count()).unwrap();
    writeln!(w, "pub const TRANS: usize = {};", nl.transistor_count()).unwrap();
    writeln!(w, "pub const VSS: usize = {vss};").unwrap();
    writeln!(w, "pub const VCC: usize = {vcc};").unwrap();
    writeln!(w, "pub const FOLDED_GATES: usize = {};", folds.len()).unwrap();
    writeln!(w, "pub const GATES_LEFT_AS_SWITCHES: usize = {not_folded};").unwrap();
    writeln!(w, "pub const ABSORBED: usize = {};", absorbed.len()).unwrap();
    writeln!(w, "pub const SWITCHES: usize = {};", switches.len()).unwrap();
    writeln!(w, "pub const DEAD: usize = {dead};").unwrap();
    writeln!(w, "pub const JUNCTIONS: usize = {};", junction_of.len()).unwrap();
    let missing: Vec<String> = (0..nl.node_count() as NodeId).filter(|&n| !nl.exists(n)).map(|n| n.to_string()).collect();
    writeln!(w, "pub const MISSING: [usize; {}] = [{}];", missing.len(), missing.join(", ")).unwrap();

    // The gate node of every transistor, for step 0 (switches follow gates).
    write!(w, "pub static GATE_OF: [u16; TRANS] = [").unwrap();
    for t in 0..nl.transistor_count() as TransId {
        write!(w, "{},", nl.transistor_gate(t)).unwrap();
    }
    writeln!(w, "];").unwrap();

    // Signal indices, numeric only.
    let node = |name: &str| nl.node(name).unwrap_or_else(|| panic!("no node {name}"));
    let bus = |prefix: &str, n: usize| -> String {
        (0..n).map(|i| node(&format!("{prefix}{i}")).to_string()).collect::<Vec<_>>().join(", ")
    };
    writeln!(w, "pub mod sig {{").unwrap();
    for s in ["clk0", "rw", "sync", "res", "irq", "nmi", "rdy", "so"] {
        writeln!(w, "    pub const {}: usize = {};", s.to_uppercase(), node(s)).unwrap();
    }
    writeln!(w, "    pub const AB: [usize; 16] = [{}];", bus("ab", 16)).unwrap();
    for (name, prefix) in [("DB", "db"), ("A", "a"), ("X", "x"), ("Y", "y"), ("S", "s"), ("PCL", "pcl"), ("PCH", "pch"), ("IR", "ir")] {
        writeln!(w, "    pub const {name}: [usize; 8] = [{}];", bus(prefix, 8)).unwrap();
    }
    writeln!(w, "}}").unwrap();

    // Step 1b: each folded gate's ground drive as a sum of products, OR'd
    // into every plane of its output; a conducting series top lends its
    // junction's charge to the output's group.
    writeln!(w, "#[inline(always)]\npub fn gate_planes(v: &[u64], p: &mut [Vec<u64>; 5]) {{").unwrap();
    for f in &folds {
        let mut terms: Vec<String> = f.singles.iter().map(|l| format!("v[{l}]")).collect();
        terms.extend(f.series.iter().map(|(a, b, _)| format!("(v[{a}] & v[{b}])")));
        let charge: Vec<String> = f.series.iter().map(|(a, _, j)| format!("(v[{j}] & v[{a}])")).collect();
        let o = f.out;
        writeln!(w, "    {{ let s = {}; p[4][{o}] |= s; p[3][{o}] |= s; p[2][{o}] |= s; p[1][{o}] |= s; p[0][{o}] |= s{}; }}",
            terms.join(" | "),
            if charge.is_empty() { String::new() } else { format!(" | {}", charge.join(" | ")) }).unwrap();
    }
    writeln!(w, "}}").unwrap();

    // Step 2: one relaxation pass over the switches, unrolled. Returns what moved.
    writeln!(w, "#[inline(always)]\npub fn spread_once(on: &[u64], p: &mut [Vec<u64>; 5]) -> u64 {{").unwrap();
    writeln!(w, "    let mut moved = 0u64;").unwrap();
    for (t, a, b, flow) in &switches {
        match flow {
            Flow::Both => writeln!(w, "    both!(on[{t}], {a}, {b}, p, moved);").unwrap(),
            Flow::C1ToC2 => writeln!(w, "    oneway!(on[{t}], {a}, {b}, p, moved);").unwrap(),
            Flow::C2ToC1 => writeln!(w, "    oneway!(on[{t}], {b}, {a}, p, moved);").unwrap(),
        }
    }
    writeln!(w, "    moved\n}}").unwrap();

    // Step 3b: junction levels. A junction joins its output's group through
    // any conducting top; otherwise a conducting bottom grounds it; otherwise
    // it keeps its charge.
    writeln!(w, "#[inline(always)]\npub fn junctions(v: &[u64], next: &mut [u64]) {{").unwrap();
    let mut by_j: HashMap<NodeId, (NodeId, Vec<NodeId>, Vec<NodeId>)> = HashMap::new();
    for f in &folds {
        for &(top, bot, j) in &f.series {
            let e = by_j.entry(j).or_insert((f.out, Vec::new(), Vec::new()));
            e.1.push(top);
            e.2.push(bot);
        }
    }
    let mut js: Vec<_> = by_j.into_iter().collect();
    js.sort_by_key(|(j, _)| *j);
    for (j, (out, tops, bots)) in js {
        let top = tops.iter().map(|l| format!("v[{l}]")).collect::<Vec<_>>().join(" | ");
        let bot = bots.iter().map(|l| format!("v[{l}]")).collect::<Vec<_>>().join(" | ");
        writeln!(w, "    {{ let top = {top}; let bot = {bot}; next[{j}] = (top & next[{out}]) | (!top & !bot & v[{j}]); }}").unwrap();
    }
    writeln!(w, "}}").unwrap();

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("kernel.rs");
    std::fs::write(&out, o).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:warning=v6502-compiled: {} gates folded ({} transistors), {} left as switches, {} switches swept, {} dead, {} junctions",
        folds.len(), absorbed.len(), not_folded, switches.len(), dead, junction_of.len()
    );
}
