//! The compiler front end: read the die through the schematic, emit the
//! kernel as Rust.
//!
//! What is emitted, and only this, so the licence check can hold it to it:
//! numbers. Node and transistor indices, the fold of each recognised gate
//! as a sum of products over node indices, the switch list, and the signal
//! indices the runtime needs. No name from the die's name table reaches the
//! generated file.

use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::PathBuf;

use v6502_netlist::schematic::Schematic;
use v6502_netlist::{mos6502, NodeId, TransId};

fn main() {
    let nl = mos6502();
    let sch = Schematic::derive(&nl);
    let (vss, vcc) = (nl.vss(), nl.vcc());
    let unresolved: HashSet<NodeId> = sch.unresolved.iter().map(|u| u.node).collect();

    // --- the fold -----------------------------------------------------
    struct Fold {
        out: NodeId,
        singles: Vec<NodeId>,
        series: Vec<(NodeId, NodeId, NodeId)>, // (top literal, bottom literal, junction)
    }
    let mut folds: Vec<Fold> = Vec::new();
    let mut absorbed: HashSet<TransId> = HashSet::new();
    let mut junction_of: HashMap<NodeId, usize> = HashMap::new();
    let mut not_folded = 0usize;

    for g in &sch.gates {
        if unresolved.contains(&g.out) {
            not_folded += 1;
            continue;
        }
        let mine: HashSet<TransId> = g.transistors.iter().copied().collect();
        let mut used: HashSet<TransId> = HashSet::new();
        let mut f = Fold { out: g.out, singles: Vec::new(), series: Vec::new() };
        for t in nl.terminals_of(g.out) {
            if !mine.contains(&t.transistor) {
                continue;
            }
            if t.other == vss {
                f.singles.push(nl.transistor_gate(t.transistor));
                used.insert(t.transistor);
            } else {
                let j = t.other;
                for u in nl.terminals_of(j) {
                    if u.other == vss && mine.contains(&u.transistor) {
                        f.series.push((nl.transistor_gate(t.transistor), nl.transistor_gate(u.transistor), j));
                        used.insert(u.transistor);
                    }
                }
                used.insert(t.transistor);
            }
        }
        if used != mine {
            // A reading this fold cannot express: leave the gate as switches
            // rather than fold it wrong.
            not_folded += 1;
            continue;
        }
        for &(_, _, j) in &f.series {
            if let Some(prev) = junction_of.insert(j, folds.len()) {
                assert_eq!(prev, folds.len(), "junction {j} shared by two gates");
            }
        }
        absorbed.extend(mine);
        folds.push(f);
    }

    // --- the switches ---------------------------------------------------
    // Everything not absorbed, minus what can never conduct or never carries
    // drive, with the rail direction the kernel computes per transistor.
    #[derive(PartialEq)]
    enum Flow {
        Both,
        C1ToC2,
        C2ToC1,
    }
    let mut switches: Vec<(TransId, NodeId, NodeId, Flow)> = Vec::new();
    let mut dead = 0usize;
    for t in 0..nl.transistor_count() as TransId {
        if absorbed.contains(&t) {
            continue;
        }
        let (g, a, b) = (nl.transistor_gate(t), nl.transistor_c1(t), nl.transistor_c2(t));
        if g == vss || (nl.is_rail(a) && nl.is_rail(b)) {
            dead += 1;
            continue;
        }
        let flow = match (nl.is_rail(a), nl.is_rail(b)) {
            (true, false) => Flow::C1ToC2,
            (false, true) => Flow::C2ToC1,
            _ => Flow::Both,
        };
        switches.push((t, a, b, flow));
    }

    // --- emit -----------------------------------------------------------
    let mut o = String::new();
    let w = &mut o;
    writeln!(w, "// Generated by build.rs from the die data through Schematic::derive. Do not edit.").unwrap();
    writeln!(w, "pub const NODES: usize = {};", nl.node_count()).unwrap();
    writeln!(w, "pub const TRANS: usize = {};", nl.transistor_count()).unwrap();
    writeln!(w, "pub const VSS: usize = {vss};").unwrap();
    writeln!(w, "pub const VCC: usize = {vcc};").unwrap();
    writeln!(w, "pub const FOLDED_GATES: usize = {};", folds.len()).unwrap();
    writeln!(w, "pub const GATES_LEFT_AS_SWITCHES: usize = {not_folded};").unwrap();
    writeln!(w, "pub const ABSORBED: usize = {};", absorbed.len()).unwrap();
    writeln!(w, "pub const SWITCHES: usize = {};", switches.len()).unwrap();
    writeln!(w, "pub const DEAD: usize = {dead};").unwrap();
    writeln!(w, "pub const JUNCTIONS: usize = {};", junction_of.len()).unwrap();
    let missing: Vec<String> = (0..nl.node_count() as NodeId).filter(|&n| !nl.exists(n)).map(|n| n.to_string()).collect();
    writeln!(w, "pub const MISSING: [usize; {}] = [{}];", missing.len(), missing.join(", ")).unwrap();

    // The switch list as data, for a GPU that cannot afford it unrolled:
    // (transistor, c1, c2, flow) with flow 0 both ways, 1 c1 drives c2, 2
    // c2 drives c1.
    write!(w, "pub static SWITCH_TABLE: [u32; {}] = [", switches.len() * 4).unwrap();
    for (t, a, b, flow) in &switches {
        let f = match flow { Flow::Both => 0, Flow::C1ToC2 => 1, Flow::C2ToC1 => 2 };
        write!(w, "{t},{a},{b},{f},").unwrap();
    }
    writeln!(w, "];").unwrap();

    // The folded gates as data, for the GPU: per gate [out, singles, series,
    // single literals..., (top, bottom, junction)...]; and the junction rule
    // as [junction, out, tops, bottoms, top literals..., bottom literals...].
    // The straight-line form is what the CPU rung runs; the driver could not
    // compile it as code.
    {
        let mut gt: Vec<u32> = Vec::new();
        for f in &folds {
            gt.push(f.out as u32);
            gt.push(f.singles.len() as u32);
            gt.push(f.series.len() as u32);
            gt.extend(f.singles.iter().map(|&l| l as u32));
            for &(a, c, j) in &f.series {
                gt.extend([a as u32, c as u32, j as u32]);
            }
        }
        writeln!(w, "pub static GATE_TABLE: [u32; {}] = [{}];", gt.len(), gt.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")).unwrap();
        let mut by_j: HashMap<NodeId, (NodeId, Vec<NodeId>, Vec<NodeId>)> = HashMap::new();
        for f in &folds {
            for &(top, bot, j) in &f.series {
                let e = by_j.entry(j).or_insert((f.out, Vec::new(), Vec::new()));
                e.1.push(top);
                e.2.push(bot);
            }
        }
        let mut js: Vec<_> = by_j.into_iter().collect();
        js.sort_by_key(|(j, _)| *j);
        let mut jt: Vec<u32> = Vec::new();
        for (j, (out, tops, bots)) in &js {
            jt.push(*j as u32);
            jt.push(*out as u32);
            jt.push(tops.len() as u32);
            jt.push(bots.len() as u32);
            jt.extend(tops.iter().map(|&l| l as u32));
            jt.extend(bots.iter().map(|&l| l as u32));
        }
        writeln!(w, "pub static JUNCTION_TABLE: [u32; {}] = [{}];", jt.len(), jt.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")).unwrap();
        // Where each gate and junction starts in its table, so threads can
        // take one each.
        let mut go: Vec<u32> = Vec::new();
        let mut i = 0usize;
        for f in &folds {
            go.push(i as u32);
            i += 3 + f.singles.len() + 3 * f.series.len();
        }
        writeln!(w, "pub static GATE_OFFSETS: [u32; {}] = [{}];", go.len(), go.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")).unwrap();
        let mut jo: Vec<u32> = Vec::new();
        let mut i = 0usize;
        for (_, (_, tops, bots)) in &js {
            jo.push(i as u32);
            i += 4 + tops.len() + bots.len();
        }
        writeln!(w, "pub static JUNCTION_OFFSETS: [u32; {}] = [{}];", jo.len(), jo.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")).unwrap();
    }

    // The gate node of every transistor, for step 0 (switches follow gates).
    write!(w, "pub static GATE_OF: [u16; TRANS] = [").unwrap();
    for t in 0..nl.transistor_count() as TransId {
        write!(w, "{},", nl.transistor_gate(t)).unwrap();
    }
    writeln!(w, "];").unwrap();

    // Signal indices, numeric only.
    let node = |name: &str| nl.node(name).unwrap_or_else(|| panic!("no node {name}"));
    let bus = |prefix: &str, n: usize| -> String {
        (0..n).map(|i| node(&format!("{prefix}{i}")).to_string()).collect::<Vec<_>>().join(", ")
    };
    writeln!(w, "pub mod sig {{").unwrap();
    for s in ["clk0", "rw", "sync", "res", "irq", "nmi", "rdy", "so"] {
        writeln!(w, "    pub const {}: usize = {};", s.to_uppercase(), node(s)).unwrap();
    }
    writeln!(w, "    pub const AB: [usize; 16] = [{}];", bus("ab", 16)).unwrap();
    for (name, prefix) in [("DB", "db"), ("A", "a"), ("X", "x"), ("Y", "y"), ("S", "s"), ("PCL", "pcl"), ("PCH", "pch"), ("IR", "ir")] {
        writeln!(w, "    pub const {name}: [usize; 8] = [{}];", bus(prefix, 8)).unwrap();
    }
    writeln!(w, "}}").unwrap();

    // Step 1b: each folded gate's ground drive as a sum of products, OR'd
    // into every plane of its output; a conducting series top lends its
    // junction's charge to the output's group.
    writeln!(w, "#[inline(always)]\npub fn gate_planes(v: &[u64], p: &mut [Vec<u64>; 5]) {{").unwrap();
    for f in &folds {
        let mut terms: Vec<String> = f.singles.iter().map(|l| format!("v[{l}]")).collect();
        terms.extend(f.series.iter().map(|(a, b, _)| format!("(v[{a}] & v[{b}])")));
        let charge: Vec<String> = f.series.iter().map(|(a, _, j)| format!("(v[{j}] & v[{a}])")).collect();
        let o = f.out;
        writeln!(w, "    {{ let s = {}; p[4][{o}] |= s; p[3][{o}] |= s; p[2][{o}] |= s; p[1][{o}] |= s; p[0][{o}] |= s{}; }}",
            terms.join(" | "),
            if charge.is_empty() { String::new() } else { format!(" | {}", charge.join(" | ")) }).unwrap();
    }
    writeln!(w, "}}").unwrap();

    // Step 2: one relaxation pass over the switches, unrolled. Returns what moved.
    writeln!(w, "#[inline(always)]\npub fn spread_once(on: &[u64], p: &mut [Vec<u64>; 5]) -> u64 {{").unwrap();
    writeln!(w, "    let mut moved = 0u64;").unwrap();
    for (t, a, b, flow) in &switches {
        match flow {
            Flow::Both => writeln!(w, "    both!(on[{t}], {a}, {b}, p, moved);").unwrap(),
            Flow::C1ToC2 => writeln!(w, "    oneway!(on[{t}], {a}, {b}, p, moved);").unwrap(),
            Flow::C2ToC1 => writeln!(w, "    oneway!(on[{t}], {b}, {a}, p, moved);").unwrap(),
        }
    }
    writeln!(w, "    moved\n}}").unwrap();

    // Step 3b: junction levels. A junction joins its output's group through
    // any conducting top; otherwise a conducting bottom grounds it; otherwise
    // it keeps its charge.
    writeln!(w, "#[inline(always)]\npub fn junctions(v: &[u64], next: &mut [u64]) {{").unwrap();
    let mut by_j: HashMap<NodeId, (NodeId, Vec<NodeId>, Vec<NodeId>)> = HashMap::new();
    for f in &folds {
        for &(top, bot, j) in &f.series {
            let e = by_j.entry(j).or_insert((f.out, Vec::new(), Vec::new()));
            e.1.push(top);
            e.2.push(bot);
        }
    }
    let mut js: Vec<_> = by_j.into_iter().collect();
    js.sort_by_key(|(j, _)| *j);
    for (j, (out, tops, bots)) in js {
        let top = tops.iter().map(|l| format!("v[{l}]")).collect::<Vec<_>>().join(" | ");
        let bot = bots.iter().map(|l| format!("v[{l}]")).collect::<Vec<_>>().join(" | ");
        writeln!(w, "    {{ let top = {top}; let bot = {bot}; next[{j}] = (top & next[{out}]) | (!top & !bot & v[{j}]); }}").unwrap();
    }
    writeln!(w, "}}").unwrap();

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("kernel.rs");
    std::fs::write(&out, o).unwrap();

    // --- the same kernel as WGSL --------------------------------------
    // One invocation owns one u32 word: 32 machines. Every per-node array is
    // laid out word-major (`base + node`), the planes as five such arrays per
    // word, and the code is the Rust code above with u32 lanes: nothing here
    // is derived a second time, both emitters walk the same folds and the
    // same switch list.
    let mut g = String::new();
    let w = &mut g;
    let n = nl.node_count();
    let tc = nl.transistor_count();
    writeln!(w, "// Generated by build.rs from the die data through Schematic::derive. Do not edit.").unwrap();
    writeln!(w, "const NODES: u32 = {n}u;\nconst TRANS: u32 = {tc}u;\nconst VSS: u32 = {vss}u;\nconst VCC: u32 = {vcc}u;").unwrap();
    
    writeln!(w, "// One WORKGROUP per word of 32 machines: the threads split the nodes,").unwrap();
    writeln!(w, "// transistors, gates and switches between them. The relaxation is a").unwrap();
    writeln!(w, "// monotone OR over the planes, so switches can be merged in parallel with").unwrap();
    writeln!(w, "// atomicOr and reach the same fixed point the serial sweep reaches.").unwrap();
    writeln!(w, "// Loop bounds travel in the uniform on purpose: as constants the driver").unwrap();
    writeln!(w, "// unrolled nested loops and ran out of memory.").unwrap();
    writeln!(w, "struct Params {{ words: u32, op: u32, max_rounds: u32, nodes: u32, trans: u32, switches: u32, gates: u32, junctions: u32 }}").unwrap();
    writeln!(w, "@group(0) @binding(0) var<uniform> params: Params;").unwrap();
    writeln!(w, "@group(0) @binding(1) var<storage, read_write> value: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(2) var<storage, read_write> pullup: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(3) var<storage, read_write> pulldown: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(4) var<storage, read_write> trans_on: array<u32>;").unwrap();
    writeln!(w, "// The planes live in workgroup memory: five per node, 34.5 KB, where atomics\n// are cheap and the working set stays on chip whatever the word count.").unwrap();
    writeln!(w, "var<workgroup> pl: array<atomic<u32>, {}>;", 5 * n).unwrap();
    writeln!(w, "@group(0) @binding(6) var<storage, read_write> nxt: array<u32>;").unwrap();
    writeln!(w, "// Memory is SPARSE per lane: one shared base image, a page table per").unwrap();
    writeln!(w, "// lane (256 entries, 0xffffffff = the base's page), and a pool of").unwrap();
    writeln!(w, "// 256-byte pages allocated copy-on-write at the first write. Each").unwrap();
    writeln!(w, "// lane's table and pages are touched only by that lane's thread, so").unwrap();
    writeln!(w, "// the one shared atomic is the allocator; a spent pool raises the").unwrap();
    writeln!(w, "// flag in pmeta[2] and drops the write, and the host REFUSES the run").unwrap();
    writeln!(w, "// on readback rather than serving memory that silently diverged.").unwrap();
    writeln!(w, "@group(0) @binding(5) var<storage, read> base: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(7) var<storage, read_write> pool: array<atomic<u32>>;").unwrap();
    writeln!(w, "@group(0) @binding(14) var<storage, read_write> ptab: array<u32>;").unwrap();
    writeln!(w, "// pmeta[0] = next free page, pmeta[1] = capacity, pmeta[2] = spent flag.").unwrap();
    writeln!(w, "@group(0) @binding(15) var<storage, read_write> pmeta: array<atomic<u32>>;").unwrap();
    writeln!(w, "@group(0) @binding(8) var<storage, read> gate_of: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(9) var<storage, read> sw: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(10) var<storage, read> gt: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(11) var<storage, read> jt: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(12) var<storage, read> go: array<u32>;").unwrap();
    writeln!(w, "@group(0) @binding(13) var<storage, read> jo: array<u32>;").unwrap();
    writeln!(w, "const SIG_CLK0: u32 = {}u;\nconst SIG_RW: u32 = {}u;", node("clk0"), node("rw")).unwrap();
    let ab: Vec<String> = (0..16).map(|i| format!("{}u", node(&format!("ab{i}")))).collect();
    let db: Vec<String> = (0..8).map(|i| format!("{}u", node(&format!("db{i}")))).collect();
    writeln!(w, "var<private> AB: array<u32, 16> = array<u32, 16>({});", ab.join(", ")).unwrap();
    writeln!(w, "var<private> DB: array<u32, 8> = array<u32, 8>({});", db.join(", ")).unwrap();
    let mstr: Vec<String> = (0..nl.node_count() as NodeId).filter(|&x| !nl.exists(x)).map(|x| format!("{x}u")).collect();
    writeln!(w, "const MISSING_N: u32 = {}u;", mstr.len()).unwrap();
    writeln!(w, "var<private> MISSING: array<u32, {}> = array<u32, {}>({});", mstr.len(), mstr.len(), mstr.join(", ")).unwrap();
    writeln!(w, r#"
const WG: u32 = 256u;
var<workgroup> acc_sw: atomic<u32>;
var<workgroup> acc_moved: atomic<u32>;
var<workgroup> acc_changed: atomic<u32>;
var<workgroup> acc_mask: atomic<u32>;
var<workgroup> acc_bits: array<atomic<u32>, 8>;
var<workgroup> uni: u32;

// A workgroup-uniform read of an accumulator: thread 0 copies it, everyone
// reads the copy after a barrier, so a loop can exit uniformly on it.
fn uniform_take(which: u32, lid: u32) -> u32 {{
  workgroupBarrier();
  if (lid == 0u) {{
    if (which == 0u) {{ uni = atomicExchange(&acc_moved, 0u); }}
    else if (which == 1u) {{ uni = atomicExchange(&acc_sw, 0u) | atomicExchange(&acc_changed, 0u); }}
    else {{ uni = atomicLoad(&acc_mask); }}
  }}
  workgroupBarrier();
  let v = workgroupUniformLoad(&uni);
  return v;
}}

fn round(b: u32, pb: u32, tb: u32, lid: u32) -> u32 {{
  // 0. switches follow gates
  var toggled: u32 = 0u;
  for (var t = lid; t < params.trans; t += WG) {{
    let g = value[b + gate_of[t]];
    toggled |= g ^ trans_on[tb + t];
    trans_on[tb + t] = g;
  }}
  atomicOr(&acc_sw, toggled);
  // 1. each node's own drive
  for (var i = lid; i < params.nodes; i += WG) {{
    let pu = pullup[b + i]; let pd = pulldown[b + i]; let v = value[b + i];
    var p4: u32 = 0u; var p3: u32 = 0u; var p2: u32 = pu; var p1: u32 = pu | pd; var p0: u32 = pu | pd | v;
    if (i == VSS) {{ p4 = 0xffffffffu; p3 = 0xffffffffu; p2 = 0xffffffffu; p1 = 0xffffffffu; p0 = 0xffffffffu; }}
    if (i == VCC) {{ p3 = 0xffffffffu; p2 = 0xffffffffu; p1 = 0xffffffffu; p0 = 0xffffffffu; }}
    atomicStore(&pl[4u * NODES + i], p4); atomicStore(&pl[3u * NODES + i], p3);
    atomicStore(&pl[2u * NODES + i], p2); atomicStore(&pl[NODES + i], p1); atomicStore(&pl[i], p0);
  }}
  workgroupBarrier();
  // 1b. the folded gates
  for (var g = lid; g < params.gates; g += WG) {{
    var i = go[g];
    let o = gt[i]; let ns = gt[i + 1u]; let nr = gt[i + 2u];
    i += 3u;
    var s: u32 = 0u;
    var charge: u32 = 0u;
    for (var k = 0u; k < ns; k++) {{ s |= value[b + gt[i]]; i += 1u; }}
    for (var k = 0u; k < nr; k++) {{
      let top = value[b + gt[i]]; let bot = value[b + gt[i + 1u]]; let j = value[b + gt[i + 2u]];
      s |= top & bot;
      charge |= j & top;
      i += 3u;
    }}
    if (s != 0u) {{
      atomicOr(&pl[4u * NODES + o], s); atomicOr(&pl[3u * NODES + o], s); atomicOr(&pl[2u * NODES + o], s);
      atomicOr(&pl[NODES + o], s);
    }}
    if ((s | charge) != 0u) {{ atomicOr(&pl[o], s | charge); }}
  }}
  workgroupBarrier();
  // 2. spread across the switches to closure, in parallel: OR is monotone.
  var spread: u32 = 0u;
  loop {{
    spread += 1u;
    var moved: u32 = 0u;
    for (var s = lid; s < params.switches; s += WG) {{
      let on = trans_on[tb + sw[4u * s]];
      if (on == 0u) {{ continue; }}
      let a = sw[4u * s + 1u];
      let c = sw[4u * s + 2u];
      let flow = sw[4u * s + 3u];
      for (var k = 0u; k < 5u; k++) {{
        let ia = k * NODES + a;
        let ic = k * NODES + c;
        let pa = atomicLoad(&pl[ia]);
        let pc = atomicLoad(&pl[ic]);
        if (flow != 2u) {{ let add = pa & on & ~pc; if (add != 0u) {{ let old = atomicOr(&pl[ic], add); moved |= add & ~old; }} }}
        if (flow != 1u) {{ let add = pc & on & ~pa; if (add != 0u) {{ let old = atomicOr(&pl[ia], add); moved |= add & ~old; }} }}
      }}
    }}
    atomicOr(&acc_moved, moved);
    let m = uniform_take(0u, lid);
    if (m == 0u || spread >= params.max_rounds) {{ break; }}
  }}
  // 3. resolve
  for (var i = lid; i < params.nodes; i += WG) {{
    let p0 = atomicLoad(&pl[i]); let p1 = atomicLoad(&pl[NODES + i]); let p2 = atomicLoad(&pl[2u * NODES + i]);
    let p3 = atomicLoad(&pl[3u * NODES + i]); let p4 = atomicLoad(&pl[4u * NODES + i]);
    var high = (p0 & ~p1) | (p2 & ~p3) | (p3 & ~p4);
    if (i == VSS) {{ high = 0u; }}
    if (i == VCC) {{ high = 0xffffffffu; }}
    nxt[b + i] = high;
  }}
  for (var m = lid; m < MISSING_N; m += WG) {{ nxt[b + MISSING[m]] = 0u; }}
  workgroupBarrier();
  // 3b. junctions
  for (var q = lid; q < params.junctions; q += WG) {{
    var i = jo[q];
    let j = jt[i]; let o = jt[i + 1u]; let nt = jt[i + 2u]; let nb = jt[i + 3u];
    i += 4u;
    var top: u32 = 0u;
    var bot: u32 = 0u;
    for (var k = 0u; k < nt; k++) {{ top |= value[b + jt[i]]; i += 1u; }}
    for (var k = 0u; k < nb; k++) {{ bot |= value[b + jt[i]]; i += 1u; }}
    nxt[b + j] = (top & nxt[b + o]) | (~top & ~bot & value[b + j]);
  }}
  workgroupBarrier();
  // 3c. commit
  var changed: u32 = 0u;
  for (var i = lid; i < params.nodes; i += WG) {{ let n = nxt[b + i]; changed |= n ^ value[b + i]; value[b + i] = n; }}
  atomicOr(&acc_changed, changed);
  return uniform_take(1u, lid);
}}

fn settle(b: u32, pb: u32, tb: u32, lid: u32) {{
  for (var r = 0u; r < params.max_rounds; r++) {{
    if (round(b, pb, tb, lid) == 0u) {{ return; }}
  }}
}}

fn read_bus8(b: u32, lane: u32) -> u32 {{
  var v: u32 = 0u;
  for (var i = 0u; i < 8u; i++) {{ v |= ((value[b + DB[i]] >> lane) & 1u) << i; }}
  return v;
}}
fn read_bus16(b: u32, lane: u32) -> u32 {{
  var v: u32 = 0u;
  for (var i = 0u; i < 16u; i++) {{ v |= ((value[b + AB[i]] >> lane) & 1u) << i; }}
  return v;
}}
fn mem_read(lane_global: u32, addr: u32) -> u32 {{
  let e = ptab[lane_global * 256u + (addr >> 8u)];
  if (e == 0xffffffffu) {{
    return (base[addr >> 2u] >> ((addr & 3u) * 8u)) & 0xffu;
  }}
  let byte = e * 256u + (addr & 0xffu);
  return (atomicLoad(&pool[byte >> 2u]) >> ((byte & 3u) * 8u)) & 0xffu;
}}
fn mem_write(lane_global: u32, addr: u32, data: u32) {{
  var e = ptab[lane_global * 256u + (addr >> 8u)];
  if (e == 0xffffffffu) {{
    // First write into this page: take a pool page, seed it from the
    // base, install it. Only this lane's thread touches this entry.
    e = atomicAdd(&pmeta[0], 1u);
    if (e >= atomicLoad(&pmeta[1])) {{
      atomicStore(&pmeta[2], 1u);
      return;
    }}
    for (var i = 0u; i < 64u; i++) {{ atomicStore(&pool[e * 64u + i], base[(addr >> 8u) * 64u + i]); }}
    ptab[lane_global * 256u + (addr >> 8u)] = e;
  }}
  let byte = e * 256u + (addr & 0xffu);
  let sh = (byte & 3u) * 8u;
  atomicAnd(&pool[byte >> 2u], ~(0xffu << sh));
  atomicOr(&pool[byte >> 2u], (data & 0xffu) << sh);
}}

// op 0: clk0 falls, then reads are serviced; op 1: clk0 rises, then writes.
@compute @workgroup_size(256)
fn half_step(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) l: vec3<u32>) {{
  let word = wid.x;
  let lid = l.x;
  let b = word * NODES;
  let pb = word * 5u * NODES;
  let tb = word * TRANS;
  if (lid == 0u) {{
    atomicStore(&acc_sw, 0u); atomicStore(&acc_moved, 0u); atomicStore(&acc_changed, 0u); atomicStore(&acc_mask, 0u);
    for (var i = 0u; i < 8u; i++) {{ atomicStore(&acc_bits[i], 0u); }}
    if (params.op == 0u) {{ pullup[b + SIG_CLK0] = 0u; pulldown[b + SIG_CLK0] = 0xffffffffu; }}
    else {{ pullup[b + SIG_CLK0] = 0xffffffffu; pulldown[b + SIG_CLK0] = 0u; }}
  }}
  workgroupBarrier();
  settle(b, pb, tb, lid);
  if (params.op == 0u) {{
    if (lid < 32u) {{
      let lane = lid;
      if (((value[b + SIG_RW] >> lane) & 1u) != 0u) {{
        atomicOr(&acc_mask, 1u << lane);
        let data = mem_read(word * 32u + lane, read_bus16(b, lane));
        for (var i = 0u; i < 8u; i++) {{ atomicOr(&acc_bits[i], ((data >> i) & 1u) << lane); }}
      }}
    }}
    let read_mask = uniform_take(2u, lid);
    if (read_mask != 0u) {{
      if (lid < 8u) {{
        let n = b + DB[lid];
        let bits = atomicLoad(&acc_bits[lid]);
        pullup[n] = (pullup[n] & ~read_mask) | (bits & read_mask);
        pulldown[n] = (pulldown[n] & ~read_mask) | (~bits & read_mask);
      }}
      workgroupBarrier();
      settle(b, pb, tb, lid);
    }}
  }} else {{
    if (lid < 32u) {{
      let lane = lid;
      if (((value[b + SIG_RW] >> lane) & 1u) == 0u) {{
        mem_write(word * 32u + lane, read_bus16(b, lane), read_bus8(b, lane));
      }}
    }}
  }}
}}
"#).unwrap();
    std::fs::write(PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("kernel.wgsl"), g).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:warning=v6502-compiled: {} gates folded ({} transistors), {} left as switches, {} switches swept, {} dead, {} junctions",
        folds.len(), absorbed.len(), not_folded, switches.len(), dead, junction_of.len()
    );
}
