#!/usr/bin/env python3
"""Produce a content-hashed, offline-capable build of web/ into dist/.

    python3 tools/build-web.py web dist

Why this exists: a service worker that caches aggressively is only safe if a
given URL's contents can never change. Hashing every asset makes that true, and
makes `immutable` caching honest. Without it a cache-first worker will
eventually pair a new .wasm with an old app.js, which fails in ways that look
like corruption rather than staleness.

Hashing is done dependency-first, so a change to a leaf ripples all the way up:

    layout.bin ─┐
    *_bg.wasm ──┴─> v6502_wasm.js ─┐
    renderer.js ──┬─────────────── ┼─> app.js ─┐
    disasm.js ────┤                ┘           ├─> index.html
    lab.js ───────┘                            │
    style.css, icons ──> manifest.webmanifest ─┤
    site-nav.js, version-footer.js ────────────┘

index.html and sw.js are deliberately NOT hashed: they are the entry points, and
are served no-cache so a deploy takes effect immediately.
"""

import hashlib
import json
import shutil
import sys
from pathlib import Path

# Emitted verbatim, with the precache list and version substituted in.
SW_TEMPLATE = """// Generated by tools/build-web.py -- do not edit by hand.
//
// Every entry in PRECACHE is content-hashed, so its bytes can never change.
// That is what makes cache-first safe here; without hashing this worker would
// eventually serve a new .wasm alongside an old app.js.

const VERSION = '%(version)s';
const CACHE = 'v6502-' + VERSION;
const PRECACHE = %(precache)s;
const PRECACHE_SET = new Set(PRECACHE.map((p) => new URL(p, self.registration.scope).href));
const SHELL = new URL('index.html', self.registration.scope).href;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
  // Deliberately no skipWaiting(): a page already running holds references to
  // the previous build's hashed URLs. Taking over mid-session and then dropping
  // the old cache in activate would pull those out from under it. The new
  // worker takes over once every tab using the old one has gone.
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
    // Safe here precisely because activation waited for the old clients.
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first, so a deploy is picked up as soon as the user is
  // online, with the cache as the offline fallback.
  //
  // The requested page is tried before SHELL. There is more than one entry
  // point now, and falling straight back to the shell meant that opening
  // blueprint.html offline silently served the explorer instead -- a wrong page
  // that renders perfectly, which is the hardest kind of failure to notice.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(req);
      } catch {
        const url = new URL(req.url);
        url.hash = '';
        url.search = '';
        return (await caches.match(url.href))
          || (await caches.match(SHELL))
          || Response.error();
      }
    })());
    return;
  }

  // Hashed assets: cache first. The URL uniquely identifies its bytes.
  if (PRECACHE_SET.has(url.href)) {
    event.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    })());
    return;
  }

  // Anything else: network, falling back to whatever we happen to hold.
  event.respondWith(fetch(req).catch(async () => (await caches.match(req)) || Response.error()));
});
"""


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:8]


class Build:
    def __init__(self, src: Path, out: Path):
        self.src = src
        self.out = out
        self.map: dict[str, str] = {}  # original relative path -> hashed relative path

    def emit(self, rel: str, data: bytes, *, hashed: bool = True) -> str:
        """Write `data` to the output, hashing the filename unless told not to."""
        p = Path(rel)
        name = f"{p.stem}.{digest(data)}{p.suffix}" if hashed else p.name
        dest_rel = str(p.with_name(name))
        dest = self.out / dest_rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        self.map[rel] = dest_rel
        return dest_rel

    def read(self, rel: str) -> bytes:
        return (self.src / rel).read_bytes()

    def copy_hashed(self, rel: str) -> str:
        return self.emit(rel, self.read(rel))

    def ref(self, rel: str) -> str:
        """The output path for an already-emitted asset."""
        if rel not in self.map:
            raise KeyError(f"{rel} has not been emitted yet -- check the ordering")
        return self.map[rel]

    def basename(self, rel: str) -> str:
        return Path(self.ref(rel)).name


def replace_once(text: str, needle: str, replacement: str, *, where: str) -> str:
    """Substitute exactly one occurrence, failing loudly otherwise.

    A silent no-op here produces a build that 404s at runtime, which is much
    harder to diagnose than a build that refuses to finish.
    """
    n = text.count(needle)
    if n != 1:
        raise SystemExit(f"build-web: expected exactly one {needle!r} in {where}, found {n}")
    return text.replace(needle, replacement)


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "web")
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "dist")

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    b = Build(src, out)

    # 1. Leaves ------------------------------------------------------------
    b.copy_hashed("layout.bin")
    b.copy_hashed("pkg/v6502_wasm_bg.wasm")
    b.copy_hashed("style.css")
    b.copy_hashed("renderer.js")
    b.copy_hashed("disasm.js")
    b.copy_hashed("lab.js")
    b.copy_hashed("version-footer.js")
    b.copy_hashed("site-nav.js")
    b.copy_hashed("programs.js")
    b.copy_hashed("blueprint.json")
    b.copy_hashed("decode.json")
    for icon in sorted((src / "icons").iterdir()):
        if icon.suffix in {".png", ".svg"}:
            b.copy_hashed(f"icons/{icon.name}")

    # 2. wasm-bindgen glue: its wasm URL is a runtime `new URL(...)`, not a
    #    module specifier, so nothing else would rewrite it.
    glue = b.read("pkg/v6502_wasm.js").decode()
    glue = replace_once(
        glue,
        "new URL('v6502_wasm_bg.wasm', import.meta.url)",
        f"new URL('{b.basename('pkg/v6502_wasm_bg.wasm')}', import.meta.url)",
        where="pkg/v6502_wasm.js",
    )
    b.emit("pkg/v6502_wasm.js", glue.encode())

    # 3. app.js: five module imports plus one runtime fetch.
    app = b.read("app.js").decode()
    for original, resolved in [
        ("./pkg/v6502_wasm.js", "./" + b.ref("pkg/v6502_wasm.js")),
        ("./renderer.js", "./" + b.ref("renderer.js")),
        ("./disasm.js", "./" + b.ref("disasm.js")),
        ("./lab.js", "./" + b.ref("lab.js")),
        ("./programs.js", "./" + b.ref("programs.js")),
    ]:
        app = replace_once(app, f"'{original}'", f"'{resolved}'", where="app.js")
    app = replace_once(app, "fetch('layout.bin')", f"fetch('{b.ref('layout.bin')}')", where="app.js")
    b.emit("app.js", app.encode())

    # 3b. blueprint.js: two module imports plus its own runtime fetch. The JSON
    #     is data the page cannot start without, so it is hashed like any other
    #     dependency rather than left mutable.
    bp = b.read("blueprint.js").decode()
    for original, resolved in [
        ("./pkg/v6502_wasm.js", "./" + b.ref("pkg/v6502_wasm.js")),
        ("./programs.js", "./" + b.ref("programs.js")),
    ]:
        bp = replace_once(bp, f"'{original}'", f"'{resolved}'", where="blueprint.js")
    bp = replace_once(bp, "fetch('blueprint.json')",
                      f"fetch('{b.ref('blueprint.json')}')", where="blueprint.js")
    b.emit("blueprint.js", bp.encode())

    # 3c. decode.js: no wasm at all -- the page is a measured table, so it needs
    #     only the mnemonics and its own data.
    dec = b.read("decode.js").decode()
    dec = replace_once(dec, "'./disasm.js'", f"'./{b.ref('disasm.js')}'", where="decode.js")
    dec = replace_once(dec, "fetch('decode.json')",
                       f"fetch('{b.ref('decode.json')}')", where="decode.js")
    b.emit("decode.js", dec.encode())

    # 4. manifest: rewrite icon paths, then hash it too.
    manifest = json.loads(b.read("manifest.webmanifest").decode())
    for entry in manifest.get("icons", []):
        entry["src"] = b.ref(entry["src"])
    b.emit("manifest.webmanifest", (json.dumps(manifest, indent=2) + "\n").encode())

    # 5. index.html: the unhashed entry point that points at everything else.
    html = b.read("index.html").decode()
    for original in ["style.css", "app.js", "version-footer.js", "site-nav.js",
                     "manifest.webmanifest",
                     "icons/icon.svg", "icons/apple-touch-icon.png"]:
        html = replace_once(html, f'"{original}"', f'"{b.ref(original)}"', where="index.html")
    b.emit("index.html", html.encode(), hashed=False)

    # 5b. blueprint.html: the second unhashed entry point. Same treatment, and
    #     it must be listed here explicitly -- build-web.py copies only the
    #     files it names, which is also why the `_`-prefixed dev harnesses
    #     cannot reach dist/.
    bph = b.read("blueprint.html").decode()
    for original in ["style.css", "blueprint.js", "version-footer.js", "site-nav.js",
                     "manifest.webmanifest",
                     "icons/icon.svg", "icons/apple-touch-icon.png"]:
        bph = replace_once(bph, f'"{original}"', f'"{b.ref(original)}"', where="blueprint.html")
    b.emit("blueprint.html", bph.encode(), hashed=False)

    dech = b.read("decode.html").decode()
    for original in ["style.css", "decode.js", "version-footer.js", "site-nav.js",
                     "manifest.webmanifest",
                     "icons/icon.svg", "icons/apple-touch-icon.png"]:
        dech = replace_once(dech, f'"{original}"', f'"{b.ref(original)}"', where="decode.html")
    b.emit("decode.html", dech.encode(), hashed=False)

    # 6. build-info.json: copied unhashed, and deliberately NOT routed through
    #    emit(), so it never enters the precache list. Everything else here is
    #    immutable-by-hash and safe to cache forever; this is the one file whose
    #    whole job is to reflect the deploy that just happened, and a worker
    #    serving yesterday's copy cache-first would make the footer lie.
    info = src / "build-info.json"
    if info.exists():
        (out / "build-info.json").write_bytes(info.read_bytes())
    else:
        print("  note: no build-info.json in source; the version footer will be "
              "empty (run tools/build-info.py first)")

    # 7. The worker, last, since it precaches everything above.
    precache = ["./"] + sorted(b.map.values())
    version = digest("\n".join(precache).encode())
    sw = SW_TEMPLATE % {
        "version": version,
        "precache": json.dumps([p if p == "./" else "./" + p for p in precache], indent=2),
    }
    b.emit("sw.js", sw.encode(), hashed=False)

    (out / "asset-manifest.json").write_text(json.dumps(b.map, indent=2) + "\n")

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"  build {version}: {len(b.map)} assets, {total / 1024:.0f} KiB")
    for original, hashed in sorted(b.map.items()):
        if original != hashed:
            print(f"    {original:34} -> {Path(hashed).name}")


if __name__ == "__main__":
    main()
