#!/usr/bin/env python3
"""The chip's recurring circuit idioms, counted -> `docs/idioms.md`.

A knowledge base of how this chip is BUILT, derived rather than recalled. Every
count here comes out of `web/*.json`; the only authored part is the one-line
"why a designer would do this", which is marked as authored the way
`block-notes.js` is, because mixing a person's reading in with the measurements
launders one into the other.

    python3 tools/export-idioms.py
"""
import json, os, sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W = os.path.join(ROOT, "web")
OUT = os.path.join(ROOT, "docs", "idioms.md")

def load(n):
    p = os.path.join(W, n)
    if not os.path.exists(p): print("FAIL missing web/%s" % n); sys.exit(1)
    return json.load(open(p))

S, D, T, G = load("schematic.json"), load("decode.json"), load("timing.json"), load("groups.json")
names, VCC, VSS = S["names"], S["vcc"], S["vss"]
owner = {n["id"]: n["owner"] for n in G["nodes"]}
gate, legs = {}, {}
for node, kind, pre, lg in S["gates"]:
    gate[node] = (S["kinds"][kind], pre); legs[node] = lg
gin = defaultdict(set)
for n, l in legs.items():
    for leg in l:
        for g in leg: gin[n].add(g)
sw, ctrl = defaultdict(list), Counter()
for c, a, b in S["switches"]:
    sw[a].append((b, c)); sw[b].append((a, c)); ctrl[c] += 1
CLOCKS = {n for n, c in ctrl.items() if c >= 40}
nm = lambda n: names[n] or "#%d" % n
addr = lambda n: "%s:#%d" % (owner.get(n, "?"), n)

STORAGE = [n for n in range(len(names))
           if n not in gate and n not in (VCC, VSS) and sw.get(n)]

def ring_depth(n):
    best = None
    for o, c in sw[n]:
        if o in (VCC, VSS) or o not in gate: continue
        frontier, seen = {o}, {o}
        for d in range(1, 4):
            nxt = set()
            for f in frontier: nxt |= gin.get(f, set())
            if n in nxt: best = d if best is None else min(best, d); break
            frontier = nxt - seen; seen |= nxt
            if not frontier: break
    return best

shape = {}
for n in STORAGE:
    parts = sw[n]
    prech = any(o == VCC and c in CLOCKS for o, c in parts)
    ctrls = {c for o, c in parts if o not in (VCC, VSS)}
    rd = ring_depth(n)
    if rd is not None and (ctrls & CLOCKS): k = "ring"
    elif rd is not None:                     k = "ring-named"
    elif prech:                              k = "precharge"
    elif len(ctrls) >= 3:                    k = "mux"
    elif (ctrls & CLOCKS) and any(o in gate for o, _ in parts): k = "latch"
    elif any(o in gate for o, _ in parts):   k = "gated"
    else:                                    k = "chain"
    shape[n] = (k, rd, len(ctrls), prech)

# The shapes must PARTITION the storage nodes: every node exactly one shape.
# Checked here rather than at the end, so a classification that drops a node
# is caught by the claim it violates instead of by whatever crashes first.
if len(shape) != len(STORAGE):
    print("FAIL classified %d of %d storage nodes" % (len(shape), len(STORAGE)))
    sys.exit(1)

cnt = Counter(v[0] for v in shape.values())
rings = [n for n in STORAGE if shape[n][0].startswith("ring")]
depths = Counter(shape[n][1] for n in rings)
fanin = Counter(shape[n][2] for n in STORAGE)
prof = Counter()
for node, kind, pre, lg in S["gates"]:
    prof[(S["kinds"][kind], tuple(sorted((len(x) for x in lg), reverse=True)))] += 1
dyn = sum(1 for node, kind, pre, lg in S["gates"] if S["kinds"][kind] == "dynamic")

# the PLA
rows = D["rows"]
named = sum(1 for r in rows if r["name"])
irgated = sum(1 for r in rows if any(b in (0, 1) for b, _ in r["ir"]))
widest = max(fanin)
jams = sum(1 for o in T["opcodes"] if o["jam"])
cyc = Counter(o["cycles"] for o in T["opcodes"] if not o["jam"])

L = []
w = L.append
w("# How this chip is built\n")
w("Generated by `tools/export-idioms.py`. Every count is derived from")
w("`web/*.json`; the **why** lines are authored and marked as such, because a")
w("person's reading and a measurement must not be laundered into each other.\n")
w("A chip designer in 1975 had no library to call. Every structure here is")
w("built from one component (a transistor that conducts when its gate is high)")
w("and one trick (a resistor to the supply that something can pull down). What")
w("follows is the vocabulary that fell out of those two things, counted.\n")

w("## 1. There is exactly one kind of gate\n")
w("NMOS builds logic one way: a pullup holds the output high, a network of")
w("transistors to ground can beat it, so **the output is low when the network")
w("conducts**. Transistors in parallel are the ORs, in series are the ANDs, and")
w("the pullup inverts the lot. Every static gate on this die is therefore an")
w("inverted sum of products.\n")
w("**There is no AND gate and no OR gate anywhere on this chip.** To get an")
w("AND you build a NOR and invert its inputs, or you invert its output. That")
w("single fact explains most of what the die looks like.\n")
w("| shape | count |")
w("|---|---|")
for k in ("inverter", "nor", "nand", "aoi"):
    w("| %s | %d |" % (k, sum(v for (kk, _), v in prof.items() if kk == k)))
w("| dynamic (no pullup at all, see idiom 3) | %d |" % dyn)
w("")
w("> **Why (authored).** A pullup costs silicon and burns current whenever the")
w("> gate is low. Series transistors are slow, because each one adds")
w("> resistance. So the cheap gate is a wide NOR and the expensive one is a")
w("> deep NAND, which is exactly the ratio the die shows: %d NORs against %d"
  % (sum(v for (kk, _), v in prof.items() if kk == "nor"),
     sum(v for (kk, _), v in prof.items() if kk == "nand")))
w("> NANDs. **The technology's cost model is visible in the gate mix.**\n")

w("## 2. Storage is a ring you can break\n")
w("The chip has %d nodes that no gate drives. They hold values, and they do it"
  % len(STORAGE))
w("in a small number of shapes:\n")
w("| shape | count | what it is |")
w("|---|---|---|")
SHAPES = [
    ("latch", "a clocked switch and a gate, no feedback: transparent while the clock is high, then holding on charge"),
    ("ring", "two inverters in a loop with a switch in it: a real memory cell"),
    ("chain", "storage joined only to storage, with no gate between"),
    ("mux", "three or more sources arbitrating for one wire"),
    ("gated", "a gate on one side, no clock"),
    ("precharge", "driven high by the clock, then pulled down or left holding"),
]
for k, why in SHAPES:
    if cnt.get(k): w("| `%s` | %d | %s |" % (k, cnt[k], why))
w("")
w("**Every single ring is two inverters deep.** %d of %d, no exceptions."
  % (depths.get(2, 0), len(rings)))
w("A register bit on this chip is: invert it, invert it again, and close the")
w("loop through a pass transistor. Open the transistor and the value")
w("circulates forever. Shut it and the bit is free to be written from a bus.")
w("Examples: `%s`.\n" % "`, `".join(nm(n) for n in rings[:8]))
w("> **Why (authored).** A static RAM cell needs six transistors. This needs")
w("> four, and two of those are the pullups you would need anyway. The price")
w("> is that the value leaks away if the loop is left open too long, which is")
w("> why this processor has a MINIMUM clock speed as well as a maximum. **The")
w("> 6502 forgets if you stop it.**\n")

w("## 3. Dynamic logic: let the clock do the work\n")
w("%d gates have no pullup at all. A clocked transistor pulls the node high on"
  % dyn)
w("one phase and the logic either pulls it down on the next or leaves it")
w("holding its charge. Same trick as the ring, applied to a gate instead of a")
w("memory cell.\n")
w("> **Why (authored).** Half the transistors and none of the standing current,")
w("> in exchange for having to keep moving. Almost every control line on this")
w("> chip works this way.\n")

w("## 4. One wire, many drivers: the bus\n")
w("A bus here is not a component. It is a wire that nothing drives, precharged")
w("high by the clock, with a pass transistor to every possible source. The")
w("decoder opens exactly one.\n")
w("| sources on one wire | how many wires |")
w("|---|---|")
for k in sorted(fanin):
    if k: w("| %d | %d |" % (k, fanin[k]))
w("")
wide = max(STORAGE, key=lambda n: shape[n][2])
srcs = sorted((nm(c), nm(o)) for o, c in sw[wide]
              if c not in CLOCKS and o not in (VCC, VSS))
w("The widest wire on the chip is `%s`, with **%d sources**, and this is the"
  % (nm(wide), shape[wide][2]))
w("list rather than a summary of it: every one is a pass transistor with a")
w("decode line of its own.\n")
w("| control line | reaches |")
w("|---|---|")
for c, o in srcs: w("| `%s` | `%s` |" % (c, o))
w("")
pairs = []
for c, _ in srcs:
    stem = c.split("_", 1)[-1]
    for c2, _ in srcs:
        s2 = c2.split("_", 1)[-1]
        if s2 != stem and sorted(s2) == sorted(stem) and (s2, stem) not in pairs:
            pairs.append((stem, s2))
if pairs:
    w("Read the names and the convention falls out: they come in **pairs**, one")
    w("to put a value on the wire and one to take it off. %s. Those names are"
      % ", ".join("`%s`/`%s`" % p for p in pairs[:4]))
    w("not ours: they are Hanson's `SOURCE/DEST` from the MOS blueprints, and")
    w("`docs/atlas.md` traces where they came from.\n")
w("> **Why (authored).** Twelve sources through twelve transistors is far")
w("> cheaper than a twelve-input multiplexer built out of gates, and it is why")
w("> the decode PLA has so many outputs: every one of those pass transistors")
w("> needs somebody to say when. **The bus is cheap and the control of it is")
w("> the expensive part.**\n")

w("## 5. Where the opcode rules actually live\n")
w("There is no lookup table and no microcode ROM in the usual sense. There is")
w("a **PLA**: a grid where the instruction register's eight bits and their")
w("complements run one way, and %d product-term wires run the other. A term" % len(rows))
w("has a pulldown transistor wherever it cares about a bit, so **a term fires")
w("when the opcode matches its pattern**, and a term that does not test a bit")
w("simply has no transistor there and matches both ways.\n")
w("| | |")
w("|---|---|")
w("| product terms | %d |" % len(rows))
w("| terms the die gives a name | %d |" % named)
w("| terms gated by IR bit 0 or 1 directly | %d |" % irgated)
w("| control lines out | %d |" % len(D["outputs"]))
w("| of those traced back to terms | %d |" % len(D["links"]))
w("")
idx = {r["name"]: i for i, r in enumerate(rows) if r["name"]}
def fires(t):
    return {o["op"] for o in D["opcodes"] if any(t in hc["r"] for hc in o["hc"])}
la, lx = idx.get("op-T0-lda"), idx.get("op-T0-ldx/tax/tsx")
both = sorted(fires(la) & fires(lx)) if la is not None and lx is not None else []
w("**The undocumented opcodes are the lesson.** Nothing on this chip checks")
w("whether an opcode is legal. `LDA` and `LDX` are two rows of the grid, and")
w("for **%d opcodes both rows match at once** (%s), so both fire and the chip"
  % (len(both), " ".join("`$%02X`" % o for o in both)))
w("loads A and X from the same fetch. That is `LAX`: not a feature and not a")
w("bug, just what a grid does when two patterns overlap. Every one of those")
w("opcodes has low two bits `%s`, which is the bit neither row constrains.\n"
  % "`, `".join(format(b, "02b") for b in sorted({o & 3 for o in both})))
w("> **Why (authored).** A PLA is a decoder you can edit with a mask change,")
w("> and it costs one transistor per condition rather than a gate per")
w("> instruction. The cost is that it does not know what an instruction IS. It")
w("> matches patterns, and every pattern it can match, it will.\n")

w("## 6. Nothing counts the cycles\n")
w("The chip has no cycle counter. It has a shift register of %d stages, and an" % len(T["stages"]))
w("instruction ends when a product term resets it. So an instruction's length")
w("is not stored anywhere: it is **how many cycles went by before something")
w("stopped the chain**.\n")
w("Measured over all 256 opcodes: %s, and **%d opcodes never finish at all**"
  % (", ".join("%d take %d cycles" % (v, k) for k, v in sorted(cyc.items())), jams))
w("because nothing ever resets their chain. Those are the JAM opcodes, and")
w("they are not a special case in the silicon. They are the absence of one.\n")
w("> **Why (authored).** A counter needs comparators and a table of lengths.")
w("> A shift register needs one transistor per stage and the decoder you")
w("> already built. **When the answer is 'do nothing special', that is usually")
w("> what the silicon does.**\n")

w("## 7. Eight of everything, except where it matters\n")
w("The datapath is eight copies of one bit slice, and the exceptions are where")
w("the design is. Bit 7 of the special bus has its own control line")
w("(`dpc19_ADDSB7`) where bits 0 to 6 share one (`dpc20_ADDSB06`): that split")
w("**is** the shifter. The address bus high byte carries constant generators on")
w("two bits only, which is how `$00` and `$01` reach it for zero-page and stack")
w("addressing.\n")
w("> **Why (authored).** Regularity is free to lay out and free to verify. So")
w("> you build eight identical slices and then spend your cleverness on the")
w("> two or three places where identical is wrong. **Look for the exceptions;")
w("> that is where the designer was thinking.**\n")

w("## Seeing it run\n")
w("Every structure above is on the running chip, at an address:\n")
w("- a register cell: `%s` (`%s`)" % (addr(rings[0]), nm(rings[0])))
w("- the widest bus wire, its sources arbitrated by decode lines")
w("- the PLA's terms, one per row, on the Decode page\n")
w("`docs/atlas.md` gives the address rubric; the chip map draws every container")
w("and the tracer lights them half-cycle by half-cycle.\n")
w("And the other direction, which is the one that makes it stick: write a")
w("program for it. Die Runner is a 6502 ROM whose screen is a page of its own")
w("memory, run on this simulation rather than on an emulator of it, so every")
w("frame is the real decode PLA matching real patterns and the real bus")
w("arbitrating between the sources listed above. `games/README.md`.\n")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(L) + "\n")
print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(L)))
print("  storage shapes partition all %d nodes: %s" % (len(STORAGE), dict(cnt)))
print("  rings all depth 2: %s" % (set(depths) == {2}))
